version: '3'

services:
  otel-load-test:
    build:
      context: ../${RUNTIME}/
      dockerfile: Dockerfile
    networks:
      - otel
    environment:
      OTEL_SERVICE_NAME: 'otel-load-test'
      OTEL_LOGS_EXPORTER: 'debug'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4317'
      OTEL_EXPERIMENTAL_RESOURCE_DISABLED_KEYS: 'process.command_line,process.command_args'
      OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: 'delta'
      OTEL_ATTRIBUTE_VALUE_LENGTH_LIMIT: 4095
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    networks:
      - otel
    volumes:
      - ./otel-config.yaml:/otel-config.yaml
    command: ["--config=/otel-config.yaml"]
    environment:
      NEW_RELIC_OTLP_ENDPOINT: ${NEW_RELIC_OTLP_ENDPOINT}
      NEW_RELIC_API_KEY: '${NEW_RELIC_API_KEY}'
    ports:
      # - 1777:1777 # pprof extension | https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/pprofextension/README.md
      # - 8888:8888 # Prometheus metrics exposed by the collector
      # - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension | https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/healthcheckextension
      - 4317:4317 # OTLP gRPC receiver
      # - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension | https://github.com/open-telemetry/opentelemetry-collector/blob/main/extension/zpagesextension/README.md

networks:
  otel:
